visor:
    image: node:7
    volumes:
        - ./client:/src
        - ./shared:/shared
    ports:
        - 0.0.0.0:8000:8000
    working_dir: /src
    command: make run

screen:
    image: node:7
    volumes:
        - ./server:/src
        - ./shared:/shared
    ports:
        - 0.0.0.0:5005:5005
    working_dir: /src
    command: make run
